Job Schedule concurrency policy
spring-cloud/spring-cloud-deployer-kubernetes pull request #495
Opened 2022-05-18 08:48 UTC by taxone

https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/494

2022-06-14 19:22 UTC, onobc requested changes
Hi @taxone

Thank you for the contribution. I apologize for the wait on the review.

2022-06-28 15:10 UTC, taxone commented on src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesScheduler.java
> +			concurrencyPolicy = this.properties.getCron().getConcurrencyPolicy();
No, it doesn't. 
The intent of that code is using the default server configuration if the value is not provided for the current schedule.
This is the default server configuration:

![image](https://user-images.githubusercontent.com/6004991/176192711-f4c5d5e6-9d96-402f-bf23-8eca78ed6d98.png)

The schedule is created without providing any concurrency policy in the deployment properties.
You can see a debugging session below:

![image](https://user-images.githubusercontent.com/6004991/176197899-93736dac-2bc6-44c4-b96a-ca63824d76fc.png)


The *scheduleProperties* map does not contain the concurrency policy. But it's present in the **KubernetesDeploymentProperties**:

![image](https://user-images.githubusercontent.com/6004991/176198419-b79ca839-7851-4bff-87e8-9fff209e30aa.png)

Do you agree?

2022-07-20 20:42 UTC, onobc commented on src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesScheduler.java
> +			concurrencyPolicy = this.properties.getCron().getConcurrencyPolicy();
Hi @taxone - got really busy over here and just picking this back up. 

Nice touch on the debugger screenshots. And yes, I do agree w/ you. I see where the scheduler props are merged w/ the current schedule props.

2022-07-20 20:43 UTC, onobc approved these changes
Nice work @taxone . Thanks again for the contribution and I apologize it took me a bit to get back to the review. Merging now.

2022-07-20 20:46 UTC, merged